apiVersion: v1
kind: Service
metadata:
  name: {{ include "genai-devops-app.fullname" . }}
  labels:
    {{- include "genai-devops-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "genai-devops-app.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}